# Generated by Django 3.2.5 on 2021-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_registerar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidimage',
            name='state',
            field=models.CharField(choices=[('lost', 'Lost'), ('search', 'Search')], default='lost', max_length=10),
        ),
    ]
