# Generated by Django 3.2.5 on 2021-07-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_registerar', '0002_kidimage_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(verbose_name='face location array')),
                ('encoding', models.TextField(verbose_name='face encoding array')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_registerar.kidimage')),
            ],
        ),
    ]
