# Generated by Django 3.2.5 on 2021-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_registerar', '0003_kidface'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidimage',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='kidimage',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
