# Generated by Django 3.2.5 on 2021-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_registerar', '0004_auto_20210720_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidimage',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidimage',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
